### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str when trying to execute sparkai in databricks

### ISSUE THREAD

**Issue by FrancescoRettondini** [databrickslabs/pyspark-ai#127]
Hello, until yesterday everything was working fine on Databricks, but at a certain point the error in the description appeared and the execution stops. 
Is it an isolated issue and I am the only one facing it?

![Screenshot 2023-09-22 at 13 42 33](https://github.com/databrickslabs/pyspark-ai/assets/92798799/7557ab11-a8d3-4aa5-86d8-bdb75a8a2775)

**Comment by gengliangwang** [comment]
Hi @FrancescoRettondini 
Thanks for reporting the issue. Could you provide the detailed stack trace? Thanks!
