### ISSUE TITLE
Facing when trying to import SparkAI from pyspark

### ISSUE THREAD

**Issue by shanmugavel04** [databrickslabs/pyspark-ai#45]
facing TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'
code used :
from pyspark_ai import SparkAI

spark_ai=SparkAI(verbose=True)
spark_ai.activate()

Also, Please clarify whether it is pyspark-ai or pyspark_ai to be imported. (need changes to the github readme).

**Comment by gengliangwang** [comment]
@shanmugavel04 
> facing TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'

Could you provide the stack trace for this one?


> Also, Please clarify whether it is pyspark-ai or pyspark_ai to be imported

The import name should be `pyspark_ai` and I think the README is correct.

**Comment by shanmugavel04** [comment]
is it 
`%sh pip install **pyspark-ai**
%python 
from **pyspark_ai** import SparkAI
 
attached the stack trace.
[english_sdk_dataclass_transform.txt](https://github.com/databrickslabs/pyspark-ai/files/11918903/english_sdk_dataclass_transform.txt)

**Comment by gengliangwang** [comment]
Hi @shanmugavel04 ,

could you try
```
%pip install pyspark-ai
```
for the installation?

`!pip` install libraries only in driver node while `%pip` install it in driver and works via nfs. It's almost always recommended to use %pip on databricks

**Comment by G0erman** [comment]
> `!pip` install libraries only in driver node while `%pip` install it in driver and works via nfs. It's almost always recommended to use %pip on databricks

It works for me!. Thank you
