### ISSUE TITLE
Uses GPT-4 by default, which may be unavailable

### ISSUE THREAD

**Issue by eduardofv** [databrickslabs/pyspark-ai#46]
It's just a minor issue, but as of today, GPT-4 is unavailable if you are not part of the limited beta. The workaround is passing the LLM to SparkAI

```
from langchain.chat_models import ChatOpenAI
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)
sa = SparkAI(llm=llm)
sa.activate()
```
I wonder if it makes sense to pass just the name of the model to SparkAI. Or make gpt-3.5 the default as it's readily available

**Comment by mengxr** [comment]
We tested GPT 3.5 but unfortunately it didn't meet the quality expectation.

**Comment by BelgiAmir** [comment]
> We tested GPT 3.5 but unfortunately it didn't meet the quality expectation.

I did some tests on that today as well.
It can manage basic requests, but I often got an invid query and errors on more complicated requests

**Comment by gengliangwang** [comment]
@eduardofv Thanks for the inputs! I have updated the README and the example notebook with how to use gpt-3.5-turbo.
The SDK works great with the gpt-4 and everything on the demo and blog post is real. That's why we recommend using gpt-4 as default.

**Comment by eduardofv** [comment]
Awesome! Can't wait to test it with GPT-4. Nevertheless, I've managed to get some small things done carefully tweaking the query prompt. Congrats on your great work!

**Comment by neox2811** [comment]
fyi: GPT-4 is now GA for paying customers. [source](https://openai.com/blog/gpt-4-api-general-availability)
