### ISSUE TITLE
Bug Report: Cannont import library after pip install

### ISSUE THREAD

**Issue by LawRachel** [databrickslabs/pyspark-ai#48]
After successfully run `pip install pyspark-ai`, still cannot run `from pyspark_ai import SparkAI`. It throws a ModuleNotFoundError: `No module named 'pyspark'` .

![image](https://github.com/databrickslabs/pyspark-ai/assets/101253617/200f2ab0-9a6b-4d99-9269-1b8b05da78f7)
![image](https://github.com/databrickslabs/pyspark-ai/assets/101253617/e761f3b0-494f-4cbf-a4d1-927116094ad0)

**Comment by sharshjot** [comment]
Hi @LawRachel ,

The error is because you don't have pyspark installed.
Try this- **pip install pyspark**

Thanks

**Comment by LawRachel** [comment]
> Hi @LawRachel ,
> 
> The error is because you don't have pyspark installed. Try this- **pip install pyspark**
> 
> Thanks

Problem solved. Thank you! @sharshjot
