### ISSUE TITLE
Unable to instantiate pyspark_ai on cloud.databricks.com

### ISSUE THREAD

**Issue by gkovaig** [databrickslabs/pyspark-ai#51]
Steps to reproduce:

Start a python notebook.

!pip install pyspark-ai
!export OPENAI_API_KEY='sk-...'
from pyspark_ai import *

TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'

**Comment by gengliangwang** [comment]
@gkovaig Thanks for the input. Yes there is a dependency conflict. I will fix it.

**Comment by gengliangwang** [comment]
Hi @gkovaig ,

could you try 
```
%pip install pyspark-ai
```
instead?
`!pip` install libraries only in driver node while `%pip` install it in driver and works via nfs. It's almost always recommended to use `%pip` on databricks

**Comment by gkovaig** [comment]
Thank yhou @gengliangwang .  I went ahead and tried it this way.  This caused a different error:

%pip install pyspark-ai
from pyspark_ai import *

1
from pyspark_ai import *
ModuleNotFoundError: No module named 'pyspark_ai'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File <command-801385568688294>:1
----> 1 from pyspark_ai import *

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

ModuleNotFoundError: No module named 'pyspark_ai'

**Comment by gengliangwang** [comment]
@gkovaig Which runtime version are you using?

**Comment by gkovaig** [comment]
@gengliangwang here are the details of the env:

12.2 LTS (includes Apache Spark 3.3.2, Scala 2.12)

<img width="1779" alt="image" src="https://github.com/databrickslabs/pyspark-ai/assets/1383586/186fe4bb-19b4-4207-9fbf-ec99ec2a1406">

**Comment by gengliangwang** [comment]
@gkovaig I can't reproduce the error with '%pip install pyspark-ai'.
Have you managed to make it work?

**Comment by gkovaig** [comment]
@gengliangwang I tried this again today.  The good news: `from pyspark_ai import *` does not throw an error any more.

In the next statement, it appears the library attempts to use gpt4 by default in this statement:
`spark_ai = SparkAI()`

As you may be aware, availability of gpt4 is limited at this point.  Is there a way to override this and pass in the model_name `model_name='gpt-3.5-turbo'` instead?

**Comment by gengliangwang** [comment]
@gkovaig FYI gpt-4 is accessible to all now: https://openai.com/blog/gpt-4-api-general-availability
If it still doesn't work, please try creating a new API key

**Comment by gkovaig** [comment]
@gengliangwang Here is my latest attempt (after using a newly generated openai api key):

!export OPENAI_API_KEY='sk-...'
from pyspark_ai import *
spark_ai = SparkAI()

ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
  
  
  
1. Can you verify that the way I'm passing the openai_api_key is correct?  (I also tried the 3 lines as three separate cells in a pyspark notebook, but the result is the same).
  
2. The call to SparkAI() does not take a named parameter called openai_api_key.

**Comment by gkovaig** [comment]
Ok, here is a solution that worked (thanks to https://github.com/sdf94/blog-posts/blob/master/english-sdk/pyspark_ai.ipynb)

`import os`
`os.environ["OPENAI_API_KEY"] = "sk-..."`
`spark_ai = SparkAI()`

This construct works without an error.


Two notes:
a) Even when environment variable OPENAI_API_KEY is set, it does not seem to be picked up correctly using the "!export ..." construct.  This may be a 'feature' of the runtime environment for Databricks Cloud, perhaps related to its use of clusters as opposed to single node hosts.
b) It is not clear to me how you would explicitly pass in `openai_api_key` or `llm` as parameters to SparkAI().

**Comment by kevisinigo** [comment]
> 

I also could not access ChatGPT 4 today, even when I created an new API key and have a paid subscription. I got the following error when running `spark_ai.create_df`:

```InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.```

Is there a way we can specify `model_name='gpt-3.5-turbo'` as @gkovaig pointed out?

**Comment by gengliangwang** [comment]
@gkovaig @kevisinigo To use `gpt-3.5-turbo`
```
from langchain.chat_models import ChatOpenAI

llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)
spark_ai = SparkAI(llm=llm)
```

**Comment by gkovaig** [comment]
Thank you, @gengliangwang - that worked!

(Note: on colab as of 2023-08-15 there is an incompatible version of `protobuf`.

I had to execute the following commands:
`%pip uninstall -y protobuf`
`%pip install --no-binary protobuf protobuf`

before this command:
`%pip install pyspark_ai`
