### ISSUE TITLE
Add an option to pass the model name as string

### ISSUE THREAD

**Issue by BelgiAmir** [databrickslabs/pyspark-ai#52]
The current SparkAI init method receives a BaseLanguageModel object and then creates a ChatOpenAI as the default.

I suggested adding an additional string type parameter to the init method (say model_name) and then create ChatOpenAI object with that model.

This will make it more streamlined to try out different open AI models and compare them.
It also removes the need for the additional important from langchain.

I ca  create a PR if that sounds helpful

**Comment by sharshjot** [comment]
Hi @BelgiAmir ,

It's already there. You can pass in the llm parameter while calling SparkAI.
`spark_ai = SparkAI(llm=ChatOpenAI(model_name='gpt-3.5-turbo', temperature=0))`

Thanks
