### ISSUE TITLE
Can pyspark-ai interact with opensource LLM models

### ISSUE THREAD

**Issue by marcelcastrobr** [databrickslabs/pyspark-ai#59]
Any other model in addition to GPT-4 that I can use with pyspark-ai?

**Comment by gengliangwang** [comment]
As of June 2023, our extensive testing suggests the most effective utilization with the English SDK and GPT-4.

By default, the SDK will use the GPT-4 model. However, you're encouraged to experiment with creating and implementing other LLMs, which can be passed during the initialization of SparkAI instances for various use-cases.

**Comment by Sassun** [comment]
Are there any benchmarks or stats with OS models like Falcon?

**Comment by gengliangwang** [comment]
@Sassun Not yet. We are focusing on new APIs and better users experience based on GPT-4.

**Comment by gengliangwang** [comment]
I am marking this one as resolved. Feel free to reopen this one if you have any more comments.
