### ISSUE TITLE
[openai.error.InvalidRequestError]: The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by Pranavchiku** [databrickslabs/pyspark-ai#65]
We have access to `gpt-4` still it throws the error. Is there any way to dynamically configure `gpt-3.5` or other LLM models?

**Comment by sharshjot** [comment]
Hi @Pranavchiku ,
try using this `spark_ai = SparkAI(llm=ChatOpenAI(model_name='gpt-3.5-turbo', temperature=0))`

Thanks

**Comment by Pranavchiku** [comment]
Thank you @sharshjot it is working :)
Do let me know if you have any easy-to-fix issues, I will be very happy to contribute
