### ISSUE TITLE
Can you retrieve the SQL query?

### ISSUE THREAD

**Issue by waddahAldrobi** [databrickslabs/pyspark-ai#66]
We have been playing around with a tool for a bit, super cool!
But is there a way to get the SQL query to help us debug?

We noticed that sometimes it's not using the partitioned columns, which doesn't scale well.

**Comment by gengliangwang** [comment]
@waddahAldrobi Thanks for the inputs!
For now, you can enable the verbose mode. For example, `spark_ai=SparkAI(verbose=true)` and there will be logs about the generated code.
I am also working on the code completion notebook magic.

**Comment by waddahAldrobi** [comment]
Woah that's awesome! 
Thank you!
