### ISSUE TITLE
How I can use this to connect Azure deployed private OpenAI model?

### ISSUE THREAD

**Issue by deeprpatel2** [databrickslabs/pyspark-ai#68]
from pyspark_ai import SparkAI
import os
#from pyspark_ai.openai import OpenAI
from langchain.chat_models import ChatOpenAI

os.environ["OPENAI_API_BASE_URL"] =""
os.environ["OPENAI_API_TYPE"]= ""
os.environ["OPENAI_API_KEY"] = "" 

# Initialize SparkAI with the ChatOpenAI model

llm = ChatOpenAI(model_name='gpt-35-turbo')

spark_ai = SparkAI(llm=llm, verbose=True)
#spark_ai = SparkAI(engine='gpt-3.5-turbo')
#spark_ai = SparkAI()

# The above Code works but fails when I use Explain or transform.

it says " Must provide an 'engine' or 'deployment_id' parameter to create a " but spark_ai = SparkAI(llm=llm, verbose=True) --it does not allow engine or deployment_id as argument

**Comment by fatmac78** [comment]
I had the same issue, but finally got this library to work with the Azure deployed private GPT model, by digging into the langchain docs.  FIrst you need to set some extra env variables - 


```python
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = ....
os.environ["OPENAI_API_BASE"] = ....
os.environ["OPENAI_API_KEY"] = ....
```

Then use the AzureOpenAI library in langchain.  This allows you to set the arguments above, set them to whatever is appropriate for your private LLM environment   

```python
# Initatiate Azure GPT 4 model versus default OpenAI
from langchain.llms import AzureOpenAI

# Create an instance of Azure OpenAI LLM
# Need to specify below format to remove errors 
llm_azure = AzureOpenAI(
    engine="gpt-4",
    model_name="gpt-4",
)
```
And finally use the instatiated Azure LLM 

```python
from pyspark_ai import SparkAI

spark_ai = SparkAI(verbose=True, llm=llm_azure)
spark_ai.activate()  # active partial functions for Spark DataFrame
```

Given Azure OpenAI is the other main place user of this library will host their LLM, I could do a PR to add it to the docs?
