### ISSUE TITLE
Rate Limit Reached Error

### ISSUE THREAD

**Issue by williamdphillips** [databrickslabs/pyspark-ai#72]
When using the 0.1.9 version of pyspark-ai, I am consistently hitting the rate limit when using a paid version of GPT 3.5. This happened the first time I attempted to use pyspark-ai with no prior utilization of ChatGPT for the day.

Image of error: 
![image](https://github.com/databrickslabs/pyspark-ai/assets/67801903/5a47ba3f-6370-4b82-85d8-a560777c610c)

Please let me know if any additional information is needed to troubleshoot the issue.

**Comment by gengliangwang** [comment]
@williamdphillips  How long is the schema string for `test_data_df`? You can check it via `spark_ai._get_df_schema(test_data_df)`
If the output is no super long, I guess your openai account has reached the soft limit and you need to increase it.

**Comment by williamdphillips** [comment]
Thanks @gengliangwang, turns out there was confusion between ChatGPT premium vs OpenAI API Premium. Started using Azure OpenAI deployments instead and no longer facing this issue.
